### ISSUE TITLE
eval_ctc.py reported bug

### ISSUE THREAD

**Issue by XJLeoYu** [kaloeffler/EmbedTrack#2]
Traceback (most recent call last):
  File "/root/autodl-tmp/MT/CT/EmbedTrack/EVAL?.py", line 6, in <module>
    calc_ctc_scores(result_dir,gt_dir)
  File "/root/autodl-tmp/MT/CT/EmbedTrack/embedtrack/ctc_metrics/eval_ctc.py", line 145, in calc_ctc_scores
    for f in os.listdir(gt_dir / "TRA") 
FileNotFoundError: [Errno 2] No such file or directory: 'EmbedTrack/ctc_raw_data/challenge/BF-C2DL-HSC_RES/01/TRA

My BF-C2DL-HSC_RES folder looks like this:
![image](https://github.com/user-attachments/assets/e960be9f-533e-40ad-aad3-02e0f1d75970)
I follow the instructions in the this repository all the way down, and failed when I run the code:

from embedtrack.ctc_metrics.eval_ctc import calc_ctc_scores
from pathlib import Path

result_dir = Path(r'EmbedTrack/ctc_raw_data/challenge/BF-C2DL-HSC_RES/01_RES')
gt_dir = Path(r'EmbedTrack/ctc_raw_data/challenge/BF-C2DL-HSC_RES/01')
calc_ctc_scores(result_dir,gt_dir)

**Comment by kaloeffler** [comment]
Dear XJLeoYu,

as the directory name reveals you are trying to evaluate on the CHALLENGE (aka the test set you would normally submit to the CTC and get evaluated on the leaderboad) not TRAIN dataset. Due to the nature of the cell tracking challenge only the TRAIN data have a ground truth available which you can download.  :) 

As this is no bug, I'm closing this issue.

**Comment by XJLeoYu** [comment]
okay, I am new bee on this filed. Dose this mean that I only need to register on ctc and upload the 01_RES and 02_RES obtained by running the "infer_all.py", I will get the evaluating results?
